CREATE TABLE [dbo].[Student]
(
	[ISBN] NVARCHAR(30) NOT NULL PRIMARY KEY,
	[FIRSTNAME] NVARCHAR(50) NOT NULL, 
	[LASTNAME] NVARCHAR(50) NOT NULL, 
	[EMAIL] NVARCHAR(320) NOT NULL, 
	[PHONENUMBER] NVARCHAR(11) NOT NULL,

	
)
